#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Najaram\WPSeederDaw\WPSeederCommand;
use Najaram\WPSeederDaw\WPDBConnection;
use Najaram\WPSeederDaw\WPSeederService;
use Symfony\Component\Console\Application;

$application = new Application();
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
// register commands
$application->add(new WPSeederCommand(new WPSeederService()));
$application->run();